services:
  - type: web
    name: invoiceparser-api
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: TURSO_DB_URL
        sync: false
      - key: PORT
        value: "8080"
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_STARTER_PRICE_ID
        sync: false
      - key: STRIPE_PRO_PRICE_ID
        sync: false
